name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  default:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - run: sbt -v --client 'show sbtVersion'
  bash:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - run: sbt -v --client 'show sbtVersion'
        shell: bash
